### ISSUE TITLE
Deleting a job with job id

### ISSUE THREAD

**Issue by juddey** [edgurgel/verk_web#87]
Hey Ed,

When you enqueue or schedule a job you get back a job id that's a big long number, however, there doesn't look like there is a way to delete a job by that ID. My ideal case is to store that number in my db table so I can delete the future scheduled job if I need to.

I had a look in verk_web, found this: https://github.com/edgurgel/verk_web/blob/3a7e3b49c284ff0679476950f0ce8e88a0383d7b/web/controllers/scheduled_controller.ex#L32. which removes a job when you pass in the whole job, on a queue named 'schedule'. 

There was also a delete_job function I found, but that required the original json, not just the ID.

Appreciate advice on where to go next.

Thanks!

**Comment by edgurgel** [comment]
Hey @juddey! 

Yeah so from what I recall the only way to delete from a Redis set is by using the exact item as reference. To remove based on the job_id we would need to scan through all items until the job_id is found. I think we ended up not implementing this because it could be a very slow operation. 

I'm happy to accept a PR that deletes a job based on the ID. We can probably have docs explaining that this might be a really slow operation?

One can implement it now using `range` function to enumerate all jobs until the job_id is found and then delete using the item?

**Comment by juddey** [comment]
Thanks for the info @edgurgel, thought there must have been some reason why you're deleting using the whole job. For my use case I'm not too worried that it would be slow. 

I'll close this off now 'cause I'm not sure if I'll get to implementing a PR in a timely fashion, and there's nothing worse than having open issues hanging around.
